### ISSUE TITLE
It doesn't select the right loader if the file has dots

### ISSUE THREAD

**Issue by iranreyes** [Jam3/preloader#12]
If the asset to preload has the format `[filename](.[A-Z]*)*.[extension]` then the loader pick up the generic one. 

After some debug I found that the get extension method needs some improvements:

```
module.exports = function getExtension (url) {
  var ext;

  if (isBase64(url)) {
    var mime = base64Mime(url);
    ext = (mime.split('/'))[1];
  } else {
    ext = url.split('.').pop();
  }

  return ext || null;
};
```

**Comment by njam3** [comment]
Fixed as of `preloader@4.0.2`
